In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv("adult.csv")
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [6]:
data.shape

(48842, 15)

In [8]:
data.describe(include='object')

,workclass,education,marital-status,occupation,relationship,race,gender,native-country,income
count,48842,48842,48842,48842,48842,48842,48842,48842,48842
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,33906,15784,22379,6172,19716,41762,32650,43832,37155

In [6]:
data['income'].value_counts()

<=50K    37155
>50K     11687
Name: income, dtype: int64

In [14]:
categorical_data = []
numerical_data = []

for col in data:
    if data[col].dtype == "object":
        categorical_data.append(col)
    else:
        numerical_data.append(col)

categorical_data.remove('income')

print(categorical_data)
print(numerical_data)

['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country']
['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']

In [19]:
from sklearn.model_selection import train_test_split

x = data.drop('income',axis=1)
y = data[['income']]

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, StandardScaler

le = LabelEncoder()
enc = OrdinalEncoder()
sc = StandardScaler()

In [23]:
X_train[categorical_data] = enc.fit_transform(X_train[categorical_data])
X_test[categorical_data] = enc.transform(X_test[categorical_data])

X_train[numerical_data] = sc.fit_transform(X_train[numerical_data])
X_test[numerical_data] = sc.transform(X_test[numerical_data])

y_train['income'] = le.fit_transform(y_train['income'])
y_test['income'] = le.transform(y_test['income'])

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier(strategy='most_frequent')
dummy_clf.fit(X_train,y_train)
preds = dummy_clf.predict(X_test)
print(f"dummy classifier accuracy is : {accuracy_score(preds,y_test)}")
print(f"dummy classifier f1_score is : {f1_score(preds,y_test)}")

dummy classifier accuracy is : 0.7655850138192241
dummy classifier f1_score is : 0.0

In [35]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
preds = rf.predict(X_test)
print(f"random forest accuracy is : {accuracy_score(preds,y_test)}")
print(f"random forest f1_score is : {f1_score(preds,y_test)}")

/home/ahmed-hereiz/.local/lib/python3.10/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

random forest accuracy is : 0.8609888422561163
random forest f1_score is : 0.6831544563695754